---
title: "Gov 50 Final Project"
author: "Ayla Aliyeva"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the effect of training and education on countries' economic growth in order to establish causality between the average number of years of schooling received by the population and countries' GDP over time. One thing I am worried about in the project is reverse causality, as I would have to find a way to minimize the possibility that it is in fact changes in GDP that affect the rate of schooling rather than vice versa.



## Finding Data and Writing a Proposal

Do higher levels of corruption lead to more frequent constitutional changes? In this study, I plan to investigate data from various countries in order to explore the relationship between levels of corruption and the frequency of constitutional changes in said countries. I hypothesize that higher levels of corruption are to be positively correlated with more frequent constitutional changes, this hypothesis being grounded in the behavioral theory that governments with higher corruption rates are more likely to revise legislation more often in order to elude legal accountability and hold on to power. My explanatory variable is the level of corruption measured using the 1980-89 Knack and Keefer measure of corruption, with a higher number indicating a higher level of corruption. My outcome variable of interest is the amount of major constitutional changes in a given country during a given decade, “major constitutional changes” being defined as “basic changes alterations in a state’s constitution”. If I observe a repeated trend of a higher count of constitutional changes in countries with more corruption in comparison to those with lower corruption, this would support my hypothesis. If, on the other hand, I see no plausible correlation between the two, or in fact, if governments with lower levels of corruption had implemented more frequent constitutional changes compared to countries with higher corruption, this would disprove my hypothesis.







